### ISSUE TITLE
Either the KeyConditions or KeyConditionExpression parameter must be specified

### ISSUE THREAD

**Issue by sarxos** [mhart/dynalite#52] opened 2016-02-29 13:28 UTC
Hello @mhart,

At the very beginning I would like to thank you for the awesome tool!

Now lets go to the problem description. I'm using [this docker](https://github.com/vsouza/docker-dynamoDB-local/blob/master/Dockerfile) to start ```dynalite```. The AWS SDK is the newest one available from Maven Central. To reproduce this case I'm using [1.10.56](http://search.maven.org/#artifactdetails|com.amazonaws|aws-java-sdk-dynamodb|1.10.56|jar). The reason I'm using Docker is due to issue #51.

Setup stack:

```plain
docker run -d -p 8080:8080 vsouza/dynamo-local --port 8080
```

Execute reproducer (code available at the end of this ticket).

Then, I'm getting this exception:

```plain
Exception in thread "main" com.amazonaws.AmazonServiceException: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 1VINPYAMXI2VWGE7BX1TLEUCKH3ONXHIGC2DTGQ4OXR3X5ZU6C1T)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1369)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1822)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:1459)
	at TestProblem.main(TestProblem.java:112)
```

From what I understand the dynalite claims I'm sending neither KeyConditions nor KeyConditionExpression, but my code to build the request for this issue is the following:

```java
QueryRequest request = new QueryRequest()
	.withTableName(table)
	.withConsistentRead(false)
	.withIndexName("rid-index")
	.withKeyConditionExpression("rid = :rid") // <-- specified
	.withExpressionAttributeValues(ImmutableMap.of(
		":rid", new AttributeValue().withN("123")))
	.withReturnConsumedCapacity(ReturnConsumedCapacity.TOTAL); 
```

And, as you can see above, the key condition expression is given as ```rid = :rid```.

By now I workaround this by not using key condition expression at all and stuck with old legacy key condition, which should not be used (according to AWS [documentation](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/QueryRequest.html#withKeyConditions%28java.util.Map%29)):

```java
QueryRequest request = new QueryRequest()
	.withTableName(table)
	.withConsistentRead(false)
	.withIndexName("rid-index")
	.withKeyConditions(ImmutableMap.of( // <-- workaround
		"rid", new Condition()
			.withComparisonOperator(ComparisonOperator.EQ)
			.withAttributeValueList(new AttributeValue().withN("123"))))
	.withReturnConsumedCapacity(ReturnConsumedCapacity.TOTAL);
```

I did take a look into the dynalite JS code and found where this error is generated but my experience with nodejs is not sufficient enough to debug this problem deeper. Just FYI, both requests works well in real DynamoDB.

Full code I used to reproduce this case:

```java

import java.util.Arrays;
import java.util.List;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.model.AttributeDefinition;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;
import com.amazonaws.services.dynamodbv2.model.KeySchemaElement;
import com.amazonaws.services.dynamodbv2.model.KeyType;
import com.amazonaws.services.dynamodbv2.model.Projection;
import com.amazonaws.services.dynamodbv2.model.ProjectionType;
import com.amazonaws.services.dynamodbv2.model.ProvisionedThroughput;
import com.amazonaws.services.dynamodbv2.model.QueryRequest;
import com.amazonaws.services.dynamodbv2.model.QueryResult;
import com.amazonaws.services.dynamodbv2.model.ReturnConsumedCapacity;
import com.google.common.collect.ImmutableMap;


public class TestProblem {

	public static void main(String[] args) {

		String access = "bubu";
		String secret = "something";

		ClientConfiguration clientConfiguration = new ClientConfiguration().withTcpKeepAlive(true);
		BasicAWSCredentials credentials = new BasicAWSCredentials(access, secret);
		AmazonDynamoDBClient client = new AmazonDynamoDBClient(credentials, clientConfiguration);

		// !!! change port to the one exposed by you docker host !!!

		client.setEndpoint("http://localhost:8080");

		String table = "test-message.3";

		// create table schema

		List<AttributeDefinition> attributes = Arrays.asList(
			new AttributeDefinition()
				.withAttributeName("mid")
				.withAttributeType("S"),
			new AttributeDefinition()
				.withAttributeName("rid")
				.withAttributeType("N"));

		List<KeySchemaElement> schema = Arrays.asList(
			new KeySchemaElement()
				.withAttributeName("mid")
				.withKeyType(KeyType.HASH));

		List<GlobalSecondaryIndex> globals = Arrays.asList(
			new GlobalSecondaryIndex()
				.withIndexName("rid-index")
				.withKeySchema(Arrays.asList(
					new KeySchemaElement()
						.withAttributeName("rid")
						.withKeyType(KeyType.HASH)))
				.withProvisionedThroughput(new ProvisionedThroughput()
					.withReadCapacityUnits(5L)
					.withWriteCapacityUnits(5L))
				.withProjection(new Projection()
					.withProjectionType(ProjectionType.ALL)));

		CreateTableRequest createRequest = new CreateTableRequest()
			.withTableName(table)
			.withAttributeDefinitions(attributes)
			.withKeySchema(schema)
			.withGlobalSecondaryIndexes(globals)
			.withProvisionedThroughput(new ProvisionedThroughput()
				.withReadCapacityUnits(5L)
				.withWriteCapacityUnits(5L));

		// create table

		try {
			new DynamoDB(client)
				.createTable(createRequest)
				.waitForActive();
		} catch (InterruptedException e) {
			throw new IllegalStateException(e);
		}

		// query table

		QueryRequest request = new QueryRequest()
			.withTableName(table)
			.withConsistentRead(false)
			.withIndexName("rid-index")
			.withKeyConditionExpression("rid = :rid")
			.withExpressionAttributeValues(ImmutableMap.of(
				":rid", new AttributeValue().withN("123")))
			.withReturnConsumedCapacity(ReturnConsumedCapacity.TOTAL);

		// this cause the error

		QueryResult result = client.query(request);

		System.out.println(result);
	}
}
```

**Comment by sarxos** [comment] 2016-02-29 13:31
After I created this ticket I found out that it may duplicate #24.

**Comment by mhart** [comment] 2016-02-29 13:46
Yep, it is a duplicate of #24 – those newer properties are not supported yet (they require writing a parser for all the supported query syntax, which is quite an undertaking).

**Closed by mhart** 2016-02-29 13:46 UTC

**Comment by sarxos** [comment] 2016-02-29 14:24
Ok, it's good to know :) Thank you!
