### ISSUE TITLE
Dynalite doesn't validate if the attribute definition doesn't exist in the keyschema

### ISSUE THREAD

**Issue by tiagobrito** [mhart/dynalite#46] opened 2016-01-28 17:10 UTC
Reference:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-AttributeDefinitions

**Comment by mhart** [comment] 2016-01-28 17:14
Have you got an example of the error that DynamoDB returns?

**Comment by tiagobrito** [comment] 2016-01-28 17:17
It return this message: "The number of attributes in key schema must match the number of attributesdefined in attribute definitions."

**Comment by mhart** [comment] 2016-01-28 17:18
Can you clarify what the issue a little? Do you mean that you're providing attributes in `AttributeDefinitions` that aren't in `KeySchema`? Or vice versa?

**Comment by mhart** [comment] 2016-01-28 17:20
I have some tests for this already – so there must be a particular case that's missing there?

https://github.com/mhart/dynalite/blob/master/test/createTable.js#L370-L386

**Comment by tiagobrito** [comment] 2016-01-28 17:20
I'm providing `AttributeDefinitions` that aren't in the `keySchema`.

**Comment by mhart** [comment] 2016-01-28 17:23
@tiagobrito Can you give the exact JSON you're using? Those tests already have an example of the behaviour you're describing (eg, `a` and `b` are in `AttributeDefinitions` but `b` is not in `KeySchema`) – so there must be something I'm missing

**Comment by mhart** [comment] 2016-01-31 20:11
@tiagobrito would you be able to give me the exact JSON you're sending to the CreateTable call?

**Comment by mhart** [comment] 2016-02-16 06:09
@tiagobrito going to close this as I can't reproduce, but am happy to reopen if you can give me the JSON that caused your issue

**Closed by mhart** 2016-02-16 06:09 UTC
